version: "3.8"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  auth-api:
    build: ./auth-api
    environment:
      - JWT_SECRET=PRFT
      - AUTH_API_PORT=8000
      - USERS_API_ADDRESS=http://users-api:8083
    ports:
      - "8000:8000"
    depends_on:
      - users-api

  users-api:
    build: ./users-api
    environment:
      - JWT_SECRET=PRFT
      - SERVER_PORT=8083
    ports:
      - "8083:8083"

  todos-api:
    build: ./todos-api
    environment:
      - JWT_SECRET=PRFT
      - TODO_API_PORT=8082
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
    ports:
      - "8082:8082"
    depends_on:
      - redis

  log-processor:
    build: ./log-message-processor
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
    depends_on:
      - redis

  frontend:
    build: ./frontend
    environment:
      - PORT=8081
      - AUTH_API_ADDRESS=http://auth-api:8000
      - TODOS_API_ADDRESS=http://todos-api:8082
    ports:
      - "8081:8081"
    depends_on:
      - auth-api
      - todos-api
