global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']

  - job_name: 'users-api'
    metrics_path: /healthz
    static_configs:
      - targets: ['users-api:8083']

  - job_name: 'circuit-breaker'
    metrics_path: /circuitz
    static_configs:
      - targets: ['users-api:8083']


