global:
  scrape_interval: 15s

scrape_configs:

  - job_name: 'users-api'
    metrics_path: /healthz
    static_configs:
      - targets: ['users-api:8083']

  - job_name: 'retry-gateway'
    metrics_path: /circuitz
    static_configs:
      - targets: ['users-api:8083']


