---
- name: Setup microservices application
  hosts: all
  become: yes
  vars:
    repo_url: https://github.com/lpinillos/microservice-app-example.git

  tasks:
    - name: Install required system packages
      apt:
        name:
          - git
          - curl
          - apt-transport-https
          - ca-certificates
          - software-properties-common
        state: present
        update_cache: yes

    - name: Install Docker and Docker Compose
      script: install-deps.sh

    - name: Clone application repository
      git:
        repo: "{{ repo_url }}"
        dest: /home/azureuser/microservice-app-example
        force: yes
      retries: 3
      delay: 10

    - name: Ensure docker-compose is available system-wide
      file:
        src: /home/azureuser/.docker/cli-plugins/docker-compose
        dest: /usr/local/bin/docker-compose
        state: link
        force: yes

    - name: Start containers with docker-compose
      command: docker-compose up -d
      args:
        chdir: /home/azureuser/microservice-app-example
      environment:
        COMPOSE_DOCKER_CLI_BUILD: 1
        DOCKER_BUILDKIT: 1