---
- name: Setup microservices application
  hosts: all
  become: yes
  vars:
    repo_url: https://github.com/lpinillos/microservice-app-example.git

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      
    - name: Install required packages
      apt:
        name:
          - git
          - curl
          - docker.io
        state: present
    
    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Add user to docker group
      user:
        name: azureuser
        groups: docker
        append: yes

    - name: Clone application repository
      git:
        repo: "{{ repo_url }}"
        dest: /home/azureuser/microservice-app-example
        force: yes

    - name: Run docker-compose
      shell: docker-compose up -d
      args:
        chdir: /home/azureuser/microservice-app-example