name: CI - Auth API
on:
  push:
    branches:
      - infra/dev
    paths:
      - auth-api/**
  pull_request:
    branches:
      - infra/dev
    paths:
      - auth-api/**
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'

      - name: Build app
        run: |
          cd auth-api
          go build -o main .

      - name: Run app (basic test)
        run: |
          cd auth-api
          ./main &
          sleep 2
          curl -I http://localhost:8000 || echo "app may require token to access"
