name: Continuous Deployment

on:
  push:
    branches:
      - 'master'
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install sshpass
        run: sudo apt-get install -y sshpass
      
      - name: Deploy to VM
        env:
          SSH_PASS: ${{ secrets.VM_PASSWORD }}
        run: |
          export SSHPASS=$SSH_PASS
          sshpass -e ssh -o StrictHostKeyChecking=no azureuser@172.178.40.170 '
            # Parar los contenedores actuales
            cd microservice-app-example
            docker-compose down
            
            cd ..
            rm -rf microservice-app-example
            
            git clone https://github.com/lpinillos/microservice-app-example.git
            
            cd microservice-app-example
            docker-compose up -d --build
          '
