name: Deploy Infrastructure and App with Ansible
on:
  push:
    paths:
      - 'infra/**'
jobs:
  full-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: Terraform Init
        run: terraform init
        working-directory: infra
      
      - name: Terraform Apply
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        run: terraform apply -auto-approve
        working-directory: infra
      
      - name: Terraform Refresh
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        run: terraform refresh
        working-directory: infra
      
      - name: Capture Terraform Output
        id: terraform_output
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        run: |
          echo "Listing all terraform outputs:"
          terraform output || echo "Error listing outputs"
          
          echo "Listing terraform state:"
          terraform state list | grep public_ip || echo "No public IP found in state"
          
          echo "Attempting to capture public IP address..."
          PUBLIC_IP=$(terraform output -raw public_ip_address 2>&1 || echo "failed")
          echo "Captured value: $PUBLIC_IP"
          
          if [[ "$PUBLIC_IP" == *"failed"* ]] || [[ "$PUBLIC_IP" == *"Error"* ]]; then
            echo "Failed to get public_ip_address output"
            echo "Debugging terraform state..."
            terraform state show azurerm_public_ip.public_ip || echo "Could not show resource details"
            exit 1
          else
            echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV
            echo "Successfully set PUBLIC_IP environment variable"
          fi
        working-directory: infra
      
      - name: Install Ansible and sshpass
        run: sudo apt-get update && sudo apt-get install -y ansible sshpass
      
      - name: Generate Ansible Inventory
        run: |
          echo "[azure_vm]" > ${{ secrets.INVENTORY_PATH }}
          echo "${{ env.PUBLIC_IP }} ansible_user=azureuser ansible_ssh_pass=${{ secrets.VM_PASSWORD }}" >> ${{ secrets.INVENTORY_PATH }}
      
      - name: Run Ansible Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
        run: |
          export ANSIBLE_ROLES_PATH=./roles
          ansible-playbook -i ${{ secrets.INVENTORY_PATH }} playbooks/install_docker.yml
        working-directory: ./ansible
