name: Deploy Infrastructure

on:
  push:
    paths:
      - 'infra/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: infra

      - name: Terraform Apply
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        run: terraform apply -auto-approve
        working-directory: infra

      - name: Get Terraform Output
        id: tf_output
        run: |
          ip=$(terraform output -raw public_ip_address | head -n1)
          echo "ip=$ip" >> $GITHUB_OUTPUT
        working-directory: infra

      - name: Install SSH tools
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy app via SSH
        run: |
          sshpass -p 'bruno1234.' ssh -o StrictHostKeyChecking=no azureuser@${{ steps.tf_output.outputs.ip }} << 'ENDSSH'
            sudo apt-get update
            sudo apt-get install -y docker.io docker-compose git

            if [ ! -d microservice-app-example ]; then
              git clone https://github.com/lpinillos/microservice-app-example.git
            else
              cd microservice-app-example && git pull
            fi

            cd microservice-app-example
            sudo docker-compose up -d
          ENDSSH
