name: Deploy Infrastructure and Configure App
on:
  push:
    paths:
      - 'infra/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Terraform
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      
      
      - name: Terraform Init
        run: terraform init
        working-directory: infra
      
      
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: infra
