name: Deploy Infrastructure with Ansible
on:
  push:
    paths:
      - 'infra/**'
      - 'ansible/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init & Apply
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        run: |
          cd infra
          terraform init
          terraform apply -auto-approve

      - name: Get VM IP
        id: get_ip
        working-directory: infra
        run: |
          IP=$(terraform output -raw public_ip_address)
          echo "VM IP: $IP"
          echo "vm_ip=$IP" >> $GITHUB_OUTPUT

      - name: Generate Ansible inventory
        run: |
          mkdir -p ansible/inventory
          sed "s/{{ vm_ip }}/${{ steps.get_ip.outputs.vm_ip }}/g" ansible/inventory-template.ini > ansible/inventory/hosts
          echo "Inventario generado:"
          cat ansible/inventory/hosts

      - name: Install Ansible and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible sshpass

      - name: Wait for VM to be ready
        run: |
          IP="${{ steps.get_ip.outputs.vm_ip }}"
          echo "Esperando a que la VM esté lista (SSH disponible)..."
          for i in {1..30}; do
            if nc -z -w 5 $IP 22; then
              echo "SSH disponible después de $i intentos"
              exit 0
            fi
            sleep 10
          done
          echo "Timeout: SSH no disponible después de 5 minutos"
          exit 1

      - name: Run Ansible playbook
        run: |
          cd ansible
          ansible-playbook -i inventory/hosts deploy.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          ANSIBLE_REMOTE_TEMP: "/tmp"
