name: Frontend

on:
  push:
    branches:
      - '**'
    paths:
      - 'frontend/**'
  pull_request:
    branches: ["**"]
    paths:
      - 'frontend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js 8.17.0
        uses: actions/setup-node@v3
        with:
          node-version: '8.17.0'

      - name: Set NPM version to 6.13.4
        run: npm install -g npm@6.13.4

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Run app and test availability
        run: |
          PORT=8081 AUTH_API_ADDRESS=http://127.0.0.1:8000 TODOS_API_ADDRESS=http://127.0.0.1:8082 npm start &
          sleep 5
          curl -I http://localhost:8081 || echo "Frontend may not be accessible or needs backend services"
