name: Python CI
on:
  push:
    branches:
        - '**'
    paths:
      - 'log-message-processor/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          cd log-message-processor
          pip install -r requirements.txt
          python -m py_compile main.py
