name: Users-api

on:
  push:
    branches:
      - '**'
    paths:
      - 'users-api/**'
  pull_request:
    branches: ["**"]
    paths:
      - 'users-api/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: users-api

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Give mvnw permission
        run: chmod +x mvnw

      - name: Build with Maven
        run: ./mvnw clean install
